<!DOCTYPE html>
<html>
<head>
<title>Main menu</title>
<link type="text/css" rel="stylesheet" href="/css/main.css">
</head>
<body>
	<div id="content">
	<h1>Choose test:</h1>
	<p><a href="?generate=common"><input type="button" value="Packet Generator" /></a></p>
	<p><a href="?generate=RMAP"><input type="button" value="RMAP Packet Generator" /></a></p>	
	<p><a href="?compare"><input type="button" value="Compare Packets" /></a></p>
	<p><a href="?parse"><input type="button" value="Packet Analysator" /></a></p>
	</div>
</body>
</html>