<!DOCTYPE html>
<html>
<head>
<title>Main menu</title>
<link type="text/css" rel="stylesheet" href="/css/main.css">
</head>
<body>
	<div id="content">
	<h1>Выберете тест:</h1>
	<p><a href="?gen" style="text-decoration: none"><input type="button" value="Simple Packet Generator" /></a></p>
	<p><a href="?compare" style="text-decoration: none"><input type="button" value="Сравнить пакеты" /></a></p>
	<p><a href="?parse" style="text-decoration: none"><input type="button" value="Анализ пакета" /></a></p>
	</div>
</body>
</html>